#!/bin/bash

set -exo pipefail

function build_image() {
    py_version="$1"
    cat Dockerfile.python-${py_version} Dockerfile.node-6.10 Dockerfile.footer | docker build --pull -t mozmeao/base:pythode-${py_version}-6.10 -
}

function push_image() {
    py_version="$1"
    docker push mozmeao/base:pythode-${py_version}-6.10
}

build_image 2.7
build_image 3.6

if [[ "$1" == "--push" ]]; then
    push_image 2.7
    push_image 3.6
fi
